In [1]:
import numpy as np

import torch

In [2]:
batch_size = 2
J = 5
hidden = 10

In [12]:
arr = [[i]*hidden for i in range(J)]

slot_e = torch.tensor(arr)  # J * hidden
print(slot_e)
print(slot_e.size())

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])
torch.Size([5, 10])


In [15]:
w = slot_e.repeat(batch_size, 1).unsqueeze(1)
print(w)
print(w.size())
w[0]

tensor([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

        [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2]],

        [[3, 3, 3, 3, 3, 3, 3, 3, 3, 3]],

        [[4, 4, 4, 4, 4, 4, 4, 4, 4, 4]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

        [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2]],

        [[3, 3, 3, 3, 3, 3, 3, 3, 3, 3]],

        [[4, 4, 4, 4, 4, 4, 4, 4, 4, 4]]])
torch.Size([10, 1, 10])


tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
hidden = torch.tensor([[1,2,3,4,5,6,7,8,9,10]]).unsqueeze(0)

hidden = hidden.repeat_interleave(J, dim=1)
print(hidden)
print(hidden.size())

tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]])
torch.Size([1, 5, 10])


In [ ]:
# encoder_output = encoder_output.repeat_interleave(J, dim=0)
# input_ids = input_ids.repeat_interleave(J, dim=0)
# input_masks = input_masks.repeat_interleave(J, dim=0)

In [44]:
gated_logit = torch.zeros(batch_size*J, 3)

gated_logit.view(batch_size, J, 3)
gated_logit.size()


torch.Size([10, 3])

In [49]:
target_ids = torch.LongTensor([[[21832, 11764,     3,     0,     0,     0],
         [21832, 11764,     3,     0,     0,     0],
         [21832, 11764,     3,     0,     0,     0],
         [21832, 11764,     3,     0,     0,     0],
         [21832, 11764,     3,     0,     0,     0],
         [21832, 11764,     3,     0,     0,     0]],

        [[21832, 11764,     3,     0,     0,     0],
         [21832, 11764,     3,     0,     0,     0],
         [21832, 11764,     3,     0,     0,     0],

         [33922,  4019, 21172,  7139,     3,     0],
         [ 6338,    30,  6242,     3,     0,     0],
         [17782,  4194,  4599,    10,  2681,     3]],

        [[21832, 11764,     3,     0,     0,     0],
         [21832, 11764,     3,     0,     0,     0],
         [21832, 11764,     3,     0,     0,     0],

         [21832, 11764,     3,     0,     0,     0],
         [21832, 11764,     3,     0,     0,     0],
         [21832, 11764,     3,     0,     0,     0]],

        [[21832, 11764,     3,     0,     0,     0],
         [21832, 11764,     3,     0,     0,     0],
         [21832, 11764,     3,     0,     0,     0],

         [21832, 11764,     3,     0,     0,     0],
         [21832, 11764,     3,     0,     0,     0],
         [21832, 11764,     3,     0,     0,     0]]])

In [53]:
print(target_ids.size())
flat = target_ids.view(-1, 1)
flat.size()

torch.Size([4, 6, 6])


torch.Size([144, 1])